# Generated by Django 4.1.12 on 2024-10-31 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tides", "0005_populate_tide_locations"),
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="tides.location",
            ),
        ),
    ]
