# Generated by Django 4.0.3 on 2022-04-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TidePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.IntegerField(db_index=True)),
                (
                    "dt",
                    models.DateTimeField(
                        help_text="America/Los_Angeles time even though it looks like UTC"
                    ),
                ),
                ("mllw_feet", models.FloatField()),
            ],
        ),
    ]
