# Generated by Django 4.0.6 on 2023-08-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tides", "0002_alter_tideprediction_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("station_id", models.IntegerField(blank=True, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("time_zone", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SunriseSunset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("dawn", models.TimeField()),
                ("sunrise", models.TimeField()),
                ("noon", models.TimeField()),
                ("sunset", models.TimeField()),
                ("dusk", models.TimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunrise_sunsets",
                        to="tides.location",
                    ),
                ),
            ],
            options={
                "unique_together": {("location", "day")},
            },
        ),
    ]
