# Generated by Django 4.0.3 on 2022-03-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fragment",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("fragment", models.TextField()),
            ],
        ),
    ]
