# Generated by Django 4.2.6 on 2023-10-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tides", "0004_add_pillar_point"),
        ("teams", "0004_teaminvitecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tides.location",
            ),
        ),
    ]
