# Generated by Django 4.1.12 on 2024-11-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0011_add_dana_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="shift_report_template",
            field=models.TextField(
                blank=True, help_text="Initial template for shift reports", null=True
            ),
        ),
    ]
