# Generated by Django 4.0.3 on 2022-03-30 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dawn", models.DateTimeField()),
                ("sunrise", models.DateTimeField()),
                ("sunset", models.DateTimeField()),
                ("dusk", models.DateTimeField()),
                ("shift_start", models.DateTimeField()),
                ("shift_end", models.DateTimeField()),
                ("mllw_feet", models.IntegerField()),
                ("lowest_tide", models.DateTimeField()),
                (
                    "stewards",
                    models.ManyToManyField(
                        related_name="shifts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
