# Generated by Django 4.0.3 on 2022-03-30 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shifts", "0002_alter_shift_lowest_tide_alter_shift_mllw_feet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="stewards",
            field=models.ManyToManyField(
                blank=True, related_name="shifts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
