# Generated by Django 4.0.3 on 2022-03-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0004_shiftchange"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="sunrise",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="sunset",
        ),
    ]
