# Generated by Django 4.0.3 on 2022-04-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0005_remove_shift_sunrise_remove_shift_sunset"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="target_stewards",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
