# Generated by Django 4.0.3 on 2022-04-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0006_shift_target_stewards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="mllw_feet",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
