# Generated by Django 4.0.3 on 2022-04-10 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shifts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shifts", "0007_alter_shift_mllw_feet"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret",
                    models.CharField(default=shifts.models.random_token, max_length=32),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_calendar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
