# Generated by Django 4.2.6 on 2023-10-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0010_set_shifts_to_pillar_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="dawn",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shift",
            name="dusk",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
