# Generated by Django 4.2.6 on 2024-02-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0008_team_calculator_settings"),
        ("shifts", "0013_shiftreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftReportQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("required", models.BooleanField(default=False)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("text", "Text"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_questions",
                        to="teams.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftReportAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_integer", models.IntegerField(blank=True, null=True)),
                ("answer_float", models.FloatField(blank=True, null=True)),
                ("answer_text", models.TextField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="shifts.shiftreportquestion",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="shifts.shiftreport",
                    ),
                ),
            ],
        ),
    ]
