# Generated by Django 4.1.12 on 2024-04-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0014_photo_shift_photos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="shifts", to="shifts.photo"
            ),
        ),
    ]
