# Generated by Django 4.1.12 on 2024-10-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0015_alter_shift_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="thumbnail_path",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
