name: Fetch weather

on:
  workflow_dispatch:
  schedule:
  # run daily at 1am San Francisco time
  - cron: '0 8 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger weather fetch
      env:
        API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      run: |-
        location_ids=$(curl -s 'https://www.pillarpointstewards.com/fetch-weather/' | \
          jq -r '.locations[].location.id')

        # Loop through each location ID
        for id in $location_ids; do
          echo "Fetching weather for location ID: $id"
          curl -X POST \
            -d "api_key=$API_KEY" \
            -d "location_id=$id" \
            'https://www.pillarpointstewards.com/fetch-weather/'
            echo -e "\nWaiting 2 seconds before next request...\n"
            sleep 2
        done
